__author__ = 'yufa'

import const

const.DEFAULT_PRODUCT_CODE = 'W'
const.DEFAULT_RELEASE_NUMBER = '4.0.0.0'
const.DEFAULT_TABLE_TYPE = 'REGULAR'
const.DEFAULT_STORY_NUMBER = 'US138139'
const.COLUMN_SNAPSHOT_ID = 'SNAPSHOT_ID'
const.TRUTH_VALUE = ('TRUE', 'T', 'YES', 'Y')
const.DICTIONARY_PRODUCT_CODE = 'Z'
const.DICTIONARY_OBJECTS = ('DB_OBJECTS', 'DB_OBJECTS_SAVED','DB_OBJECTS_UPGRADE','DB_TABLE_COLUMNS',
                            'DB_TABLE_COLUMNS_SAVED','DB_TABLE_COLUMNS_UPGRADE', 'APPLICATION')
const.PLSQL_PACKAGE = 'PACKAGE'
const.PLSQL_PROCEDURE = 'PROCEDURE'
const.PLSQL_TYPE = 'TYPE'
const.PLSQL_FUNCTION = 'FUNCTION'
const.PLSQL_SEQUENCE = 'SEQUENCE'
const.PLSQL_TRIGGER = 'TRIGGER'